version: "3"

services:
  edu-dashboard:
    image: ${EDU_DASHBOARD_IMAGE}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
        CONFIG_HOST: ${CONFIG_HOST}
        ADAPTER_HOST: ${ADAPTER_HOST}
        ADAPTER_TOKEN: ${ADAPTER_TOKEN}
        COURSE_ID: ${COURSE_ID}
    ports:
      - ${HOST_PORT:-8000}:3000
    volumes:
      - .htpasswd:/etc/nginx/.htpasswd:ro
